[package]
name = "scoped_threadpool"
version = "0.1.6"
authors = ["Marvin Löbel <loebel.marvin@gmail.com>"]
license = "MIT"
build = "build.rs"

description = "A library for scoped and cached threadpools."
readme = "README.md"
documentation = "http://kimundi.github.io/scoped-threadpool-rs/scoped_threadpool/index.html"

repository = "https://github.com/Kimundi/scoped-threadpool-rs"
keywords = ["thread", "scoped", "pool", "cached", "threadpool"]

[build-dependencies]
rustc_version = "0.1"

[dev-dependencies]
lazy_static = "*"

[features]
nightly = []
